# Generated by Django 3.2.3 on 2021-05-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.WbhJPOi8PiEDjZuFpEthMwHaE8%26pid%3DApi&f=1', max_length=500),
        ),
    ]
